import { MayoristasCollection } from "./MayoristasProducts";

export const LastCollectionMayoristas: MayoristasCollection = {
    "Casio Retro": [
        {
            "id": "CSRM101",
            "name": "Casio Retro",
            "color": "Negro con detalles dorados",
            "description": "Este reloj Casio presenta un diseño clásico. Su caja de forma cuadrada mantiene una estética simple y funcional, acompañada de una pantalla digital clara. Incorpora funciones prácticas como alarma, cronómetro e iluminación.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/casio+retro+1.JPG",
            "price": 40000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "CSRM102",
            "name": "Casio Retro",
            "color": "Dorado",
            "description": "Este reloj Casio presenta un diseño clásico. Su caja de forma cuadrada mantiene una estética simple y funcional, acompañada de una pantalla digital clara. Incorpora funciones prácticas como alarma, cronómetro e iluminación.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/casio+retro+2.JPG",
            "price": 40000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "CSRM103",
            "name": "Casio Retro",
            "color": "Negro",
            "description": "Este reloj Casio presenta un diseño clásico. Su caja de forma cuadrada mantiene una estética simple y funcional, acompañada de una pantalla digital clara. Incorpora funciones prácticas como alarma, cronómetro e iluminación.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/casio+retro+3.JPG",
            "price": 40000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "CSRM104",
            "name": "Casio Retro",
            "color": "Oro rosa",
            "description": "Este reloj Casio presenta un diseño clásico. Su caja de forma cuadrada mantiene una estética simple y funcional, acompañada de una pantalla digital clara. Incorpora funciones prácticas como alarma, cronómetro e iluminación.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/casio+retro+4.JPG",
            "price": 40000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "CSRM105",
            "name": "Casio Retro",
            "color": "Plateado",
            "description": "Este reloj Casio presenta un diseño clásico. Su caja de forma cuadrada mantiene una estética simple y funcional, acompañada de una pantalla digital clara. Incorpora funciones prácticas como alarma, cronómetro e iluminación.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/casio+retro+5.JPG",
            "price": 40000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        }
    ],
    "Mulco": [
        {
            "id": "MLCM101",
            "name": "Mulco para dama",
            "color": "Dorado con detalles de color rosa",
            "description": "Este reloj Mulco destaca por su diseño elegante y lleno de detalles que resaltan su estilo femenino y sofisticado. Su carátula incorpora formas y relieves que crean una apariencia dinámica y moderna, acompañada de indicadores bien definidos y una ventana de fecha integrada de manera armoniosa.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/mulco+1.JPG",
            "price": 55000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "MLCM102",
            "name": "Mulco para dama",
            "color": "Plateado",
            "description": "Este reloj Mulco destaca por su diseño elegante y lleno de detalles que resaltan su estilo femenino y sofisticado. Su carátula incorpora formas y relieves que crean una apariencia dinámica y moderna, acompañada de indicadores bien definidos y una ventana de fecha integrada de manera armoniosa.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/mulco+2.JPG",
            "price": 55000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "MLCM103",
            "name": "Mulco para dama",
            "color": "Plateado con detalles de color morado",
            "description": "Este reloj Mulco destaca por su diseño elegante y lleno de detalles que resaltan su estilo femenino y sofisticado. Su carátula incorpora formas y relieves que crean una apariencia dinámica y moderna, acompañada de indicadores bien definidos y una ventana de fecha integrada de manera armoniosa.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/mulco+3.JPG",
            "price": 55000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "MLCM104",
            "name": "Mulco para dama",
            "color": "Dorado con detalles de color morado",
            "description": "Este reloj Mulco destaca por su diseño elegante y lleno de detalles que resaltan su estilo femenino y sofisticado. Su carátula incorpora formas y relieves que crean una apariencia dinámica y moderna, acompañada de indicadores bien definidos y una ventana de fecha integrada de manera armoniosa.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/mulco+4.JPG",
            "price": 55000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        }
    ],
    "Q&Q": [
        {
            "id": "Q&QFLM101",
            "name": "Q&Q para dama",
            "color": "Plateado",
            "description": "Este reloj Q&Q presenta un diseño delicado y minimalista que resalta por su elegancia y simplicidad. Su carátula incorpora un patrón radial que aporta profundidad visual y un estilo sutilmente moderno, acompañado de marcadores finos que permiten una lectura clara del tiempo",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/Q%26Q+fondo+lineas+1.JPG",
            "price": 55000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "Q&QFLM102",
            "name": "Q&Q para dama",
            "color": "Dorado con detalles en azul",
            "description": "Este reloj Q&Q presenta un diseño delicado y minimalista que resalta por su elegancia y simplicidad. Su carátula incorpora un patrón radial que aporta profundidad visual y un estilo sutilmente moderno, acompañado de marcadores finos que permiten una lectura clara del tiempo",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/Q%26Q+fondo+lineas+2.JPG",
            "price": 55000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "Q&QFLM103",
            "name": "Q&Q para dama",
            "color": "Plateado con detalles en rosa",
            "description": "Este reloj Q&Q presenta un diseño delicado y minimalista que resalta por su elegancia y simplicidad. Su carátula incorpora un patrón radial que aporta profundidad visual y un estilo sutilmente moderno, acompañado de marcadores finos que permiten una lectura clara del tiempo",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/Q%26Q+fondo+lineas+3.JPG",
            "price": 55000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "Q&QFLM104",
            "name": "Q&Q para dama",
            "color": "Plateado con detalles en azul",
            "description": "Este reloj Q&Q presenta un diseño delicado y minimalista que resalta por su elegancia y simplicidad. Su carátula incorpora un patrón radial que aporta profundidad visual y un estilo sutilmente moderno, acompañado de marcadores finos que permiten una lectura clara del tiempo",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/Q%26Q+fondo+lineas+4.JPG",
            "price": 55000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        }
    ],
    "Orient": [
        {
            "id": "ORTM101",
            "name": "Orient para dama",
            "color": "Plateado con detalles en rojo",
            "description": "Este reloj Orient combina elegancia clásica con la precisión de un movimiento automático. La caja mantiene líneas limpias y equilibradas que resaltan su estilo refinado, mientras que la pulsera metálica completa el conjunto con un acabado sólido y cómodo.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/orient+dama+1.JPG",
            "price": 40000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "ORTM102",
            "name": "Orient para dama",
            "color": "Plateado",
            "description": "Este reloj Orient combina elegancia clásica con la precisión de un movimiento automático. La caja mantiene líneas limpias y equilibradas que resaltan su estilo refinado, mientras que la pulsera metálica completa el conjunto con un acabado sólido y cómodo.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/orient+dama+2.JPG",
            "price": 40000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "ORTM103",
            "name": "Orient para dama",
            "color": "Dorado con detalles en negro",
            "description": "Este reloj Orient combina elegancia clásica con la precisión de un movimiento automático. La caja mantiene líneas limpias y equilibradas que resaltan su estilo refinado, mientras que la pulsera metálica completa el conjunto con un acabado sólido y cómodo.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/orient+dama+3.JPG",
            "price": 40000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "ORTM104",
            "name": "Orient para dama",
            "color": "Dorado con detalles en azul",
            "description": "Este reloj Orient combina elegancia clásica con la precisión de un movimiento automático. La caja mantiene líneas limpias y equilibradas que resaltan su estilo refinado, mientras que la pulsera metálica completa el conjunto con un acabado sólido y cómodo.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/orient+dama+4.JPG",
            "price": 40000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "ORTM105",
            "name": "Orient para dama",
            "color": "Plateado con detalles en negro",
            "description": "Este reloj Orient combina elegancia clásica con la precisión de un movimiento automático. La caja mantiene líneas limpias y equilibradas que resaltan su estilo refinado, mientras que la pulsera metálica completa el conjunto con un acabado sólido y cómodo.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/orient+dama+5.JPG",
            "price": 40000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "ORTM106",
            "name": "Orient para dama",
            "color": "Dorado con detalles en dorado y verde",
            "description": "Este reloj Orient combina elegancia clásica con la precisión de un movimiento automático. La caja mantiene líneas limpias y equilibradas que resaltan su estilo refinado, mientras que la pulsera metálica completa el conjunto con un acabado sólido y cómodo.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/orient+dama+6.JPG",
            "price": 40000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "ORTM107",
            "name": "Orient para dama",
            "color": "Dorado con detalles en blanco",
            "description": "Este reloj Orient combina elegancia clásica con la precisión de un movimiento automático. La caja mantiene líneas limpias y equilibradas que resaltan su estilo refinado, mientras que la pulsera metálica completa el conjunto con un acabado sólido y cómodo.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/orient+dama+7.JPG",
            "price": 40000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "ORTM108",
            "name": "Orient para dama",
            "color": "Dorado",
            "description": "Este reloj Orient combina elegancia clásica con la precisión de un movimiento automático. La caja mantiene líneas limpias y equilibradas que resaltan su estilo refinado, mientras que la pulsera metálica completa el conjunto con un acabado sólido y cómodo.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/orient+dama+8.JPG",
            "price": 40000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        }
    ],
    "Audemars Piguet": [
        {
            "id": "APCM101",
            "name": "Audemars Piguet Cubano",
            "color": "Dorado",
            "description": "Este modelo destaca por su diseño imponente y lleno de detalles que reflejan un estilo audaz y sofisticado. La caja presenta un bisel decorado con múltiples incrustaciones que aportan un brillo intenso y una presencia llamativa en la muñeca.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/ap+cubano+1.JPG",
            "price": 65000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "APCM102",
            "name": "Audemars Piguet Cubano",
            "color": "Plateado",
            "description": "Este modelo destaca por su diseño imponente y lleno de detalles que reflejan un estilo audaz y sofisticado. La caja presenta un bisel decorado con múltiples incrustaciones que aportan un brillo intenso y una presencia llamativa en la muñeca.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/ap+cubano+2.JPG",
            "price": 65000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        },
        {
            "id": "APCM103",
            "name": "Audemars Piguet Cubano",
            "color": "Plateado con detalles dorados",
            "description": "Este modelo destaca por su diseño imponente y lleno de detalles que reflejan un estilo audaz y sofisticado. La caja presenta un bisel decorado con múltiples incrustaciones que aportan un brillo intenso y una presencia llamativa en la muñeca.",
            "presentacion": "Incluye caja de presentacion",
            "imgUrl": "https://relojes-s-l.s3.us-west-1.amazonaws.com/MAYORISTAS/ap+cubano+3.JPG",
            "price": 65000,
            "notes": "Recuerda confirmar por nuestra linea de whatsapp por disponibilidad.",
        }
    ]
}
